-- 1. Remove Agendamentos e Auditoria
DROP TABLE TB_AGENDAMENTO CASCADE CONSTRAINTS;
DROP TABLE TB_AUDITORIA CASCADE CONSTRAINTS;
DROP SEQUENCE SQ_AUDITORIA;

-- 2. Remove Procedures e Functions
DROP FUNCTION FN_CALCULA_DURACAO_TOTAL;
-- Se você criou as procedures de auditoria da pág 9, adicione os nomes delas abaixo:
-- DROP PROCEDURE SP_AUDITA_AGENDAMENTO;

-- 3. Remove Unidades e Salas
DROP TABLE TB_SALA CASCADE CONSTRAINTS;
DROP TABLE TB_UNIDADE_SAUDE CASCADE CONSTRAINTS;

-- 4. Remove Usuários e Herança
DROP TABLE TB_PACIENTE_ALERGIAS CASCADE CONSTRAINTS;
DROP TABLE TB_PACIENTE CASCADE CONSTRAINTS;
DROP TABLE TB_COLABORADOR CASCADE CONSTRAINTS;
DROP TABLE TB_ADMIN CASCADE CONSTRAINTS;
DROP TABLE TB_USUARIO CASCADE CONSTRAINTS;

-- 5. O MAIS IMPORTANTE: Resetar o Flyway
DROP TABLE "RM559728"."flyway_schema_history" CASCADE CONSTRAINTS;

-- 6. Faxina final
PURGE RECYCLEBIN;
COMMIT;