-- 1. Tabela Base (USUARIO)
-- Alterado para BY DEFAULT para permitir a carga inicial com IDs fixos na V2
CREATE TABLE TB_USUARIO (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100) NOT NULL UNIQUE,
    senha VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL
);

-- 2. Tabela Admin (Herança - Tabela Filha)
CREATE TABLE TB_ADMIN (
    usuario_id NUMBER PRIMARY KEY,
    CONSTRAINT fk_admin_usuario FOREIGN KEY (usuario_id) REFERENCES TB_USUARIO(id) ON DELETE CASCADE
);

-- 3. Tabela Colaborador (Herança - Tabela Filha)
CREATE TABLE TB_COLABORADOR (
    usuario_id NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) NOT NULL UNIQUE,
    tipo_colaborador VARCHAR2(30) NOT NULL,
    CONSTRAINT fk_colaborador_usuario FOREIGN KEY (usuario_id) REFERENCES TB_USUARIO(id) ON DELETE CASCADE
);

-- 4. Tabela Paciente (Herança - Tabela Filha)
CREATE TABLE TB_PACIENTE (
    usuario_id NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    cpf VARCHAR2(14) NOT NULL UNIQUE,
    tipo_sanguineo VARCHAR2(20),
    altura NUMBER(3,2),
    CONSTRAINT fk_paciente_usuario FOREIGN KEY (usuario_id) REFERENCES TB_USUARIO(id) ON DELETE CASCADE
);

-- 5. Tabela de Alergias (Relacionamento One-to-Many / ElementCollection)
CREATE TABLE TB_PACIENTE_ALERGIAS (
    paciente_id NUMBER NOT NULL,
    alergia VARCHAR2(100),
    CONSTRAINT fk_alergias_paciente FOREIGN KEY (paciente_id) REFERENCES TB_PACIENTE(usuario_id) ON DELETE CASCADE
);

COMMIT;