-- 1. INSERINDO USUÁRIOS (Sequence SQ_USUARIO deve estar criada na V1)
-- Admins (IDs 1 a 5)
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (1, 'admin1@medix.com', '123456', 'ADMIN');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (2, 'admin2@medix.com', '123456', 'ADMIN');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (3, 'admin3@medix.com', '123456', 'ADMIN');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (4, 'admin4@medix.com', '123456', 'ADMIN');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (5, 'admin5@medix.com', '123456', 'ADMIN');

-- Colaboradores (IDs 6 a 10)
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (6, 'medico1@medix.com', '123456', 'COLABORADOR');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (7, 'medico2@medix.com', '123456', 'COLABORADOR');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (8, 'recepcao1@medix.com', '123456', 'COLABORADOR');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (9, 'medico3@medix.com', '123456', 'COLABORADOR');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (10, 'recepcao2@medix.com', '123456', 'COLABORADOR');

-- Pacientes (IDs 11 a 15)
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (11, 'paciente1@gmail.com', '123456', 'PACIENTE');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (12, 'paciente2@gmail.com', '123456', 'PACIENTE');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (13, 'paciente3@gmail.com', '123456', 'PACIENTE');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (14, 'paciente4@gmail.com', '123456', 'PACIENTE');
INSERT INTO TB_USUARIO (id, email, senha, role) VALUES (15, 'paciente5@gmail.com', '123456', 'PACIENTE');

-- 2. TABELA FILHA: TB_ADMIN
INSERT INTO TB_ADMIN (usuario_id) VALUES (1);
INSERT INTO TB_ADMIN (usuario_id) VALUES (2);
INSERT INTO TB_ADMIN (usuario_id) VALUES (3);
INSERT INTO TB_ADMIN (usuario_id) VALUES (4);
INSERT INTO TB_ADMIN (usuario_id) VALUES (5);

-- 3. TABELA FILHA: TB_COLABORADOR
-- Adicionado especialidades nos nomes para o teste de agendamento funcionar
INSERT INTO TB_COLABORADOR (usuario_id, nome, cpf, tipo_colaborador) VALUES (6, 'Dr. Mateus Lima - Cardiologia', '11122233344', 'OPERACIONAL');
INSERT INTO TB_COLABORADOR (usuario_id, nome, cpf, tipo_colaborador) VALUES (7, 'Dra. Ana Costa - Clinica Geral', '22233344455', 'OPERACIONAL');
INSERT INTO TB_COLABORADOR (usuario_id, nome, cpf, tipo_colaborador) VALUES (8, 'Carlos Souza', '33344455566', 'ADMINISTRATIVO');
INSERT INTO TB_COLABORADOR (usuario_id, nome, cpf, tipo_colaborador) VALUES (9, 'Dr. Ricardo Oliveira - Pediatria', '44455566677', 'OPERACIONAL');
INSERT INTO TB_COLABORADOR (usuario_id, nome, cpf, tipo_colaborador) VALUES (10, 'Mariana Santos', '55566677788', 'ADMINISTRATIVO');

-- 4. TABELA FILHA: TB_PACIENTE
INSERT INTO TB_PACIENTE (usuario_id, nome, cpf, tipo_sanguineo, altura) VALUES (11, 'Joao Silva', '12312312311', 'O_POSITIVO', 1.75);
INSERT INTO TB_PACIENTE (usuario_id, nome, cpf, tipo_sanguineo, altura) VALUES (12, 'Maria Oliveira', '23423423422', 'A_NEGATIVO', 1.62);
INSERT INTO TB_PACIENTE (usuario_id, nome, cpf, tipo_sanguineo, altura) VALUES (13, 'Pedro Rocha', '34534534533', 'B_POSITIVO', 1.80);
INSERT INTO TB_PACIENTE (usuario_id, nome, cpf, tipo_sanguineo, altura) VALUES (14, 'Juliana Lima', '45645645644', 'AB_POSITIVO', 1.68);
INSERT INTO TB_PACIENTE (usuario_id, nome, cpf, tipo_sanguineo, altura) VALUES (15, 'Lucas Mendes', '56756756755', 'O_NEGATIVO', 1.72);

-- 5. ALERGIAS
INSERT INTO TB_PACIENTE_ALERGIAS (paciente_id, alergia) VALUES (11, 'Dipirona');
INSERT INTO TB_PACIENTE_ALERGIAS (paciente_id, alergia) VALUES (11, 'Poeira');
INSERT INTO TB_PACIENTE_ALERGIAS (paciente_id, alergia) VALUES (12, 'Lactose');

ALTER TABLE TB_USUARIO MODIFY (id GENERATED BY DEFAULT AS IDENTITY (START WITH 16));

COMMIT;